{"uid":"382d6e52f6911278","name":"test_method[启用组织 01]","fullName":"testcases.test_A.test_organization.test_enableOrganization.TestCaseCommon#test_method","historyId":"68e270a7b28188159f0ae6eeeb600028","time":{"start":1686643269767,"stop":1686643269767,"duration":0},"status":"broken","statusMessage":"pymysql.err.OperationalError: (1049, \"Unknown database 'data_operation_open_platform'\")","statusTrace":"kwargs = {'apis': [{'assert': [{'expect': 200, 'type': 'status'}, {'expect': '操作成功', 'name': 'message', 'type': 'sys'}], 'data'...on'}, 'name': '启用组织 01', 'setup': [{'sqls': 'update ums_organization set is_able = 0 where id = 35;', 'type': 'db'}]}]}\n\n    @pytest.fixture\n    def my_fixture(kwargs):\n        # 实例化HTTPClient,用于发送请求\n        http_client = HTTPClient_A()\n        # 实例化MySQLClient客户端\n        mysql_client = MySQLClient()\n    \n        # 1.处理setup部分\n    \n        execute_sql = kwargs[\"apis\"][0]\n        for item in execute_sql.get(\"setup\", \"\") :\n            if item.get(\"type\") == \"api\" :\n                http_client.request(**item.get(\"data\"))\n            elif item.get(\"type\") == \"db\" :\n>               mysql_client.execute(item.get(\"sqls\"))\n\ntestcases\\conftest.py:31: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nlib\\different_db\\mysqlclient_A.py:38: in execute\n    with pymysql.connect(host=self.host,\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\connections.py:352: in __init__\n    self.connect()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\connections.py:636: in connect\n    self._request_authentication()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\connections.py:911: in _request_authentication\n    auth_packet = self._read_packet()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\connections.py:729: in _read_packet\n    packet.raise_for_error()\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\protocol.py:221: in raise_for_error\n    err.raise_mysql_exception(self._data)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ndata = b\"\\xff\\x19\\x04#42000Unknown database 'data_operation_open_platform'\"\n\n    def raise_mysql_exception(data):\n        errno = struct.unpack(\"<h\", data[1:3])[0]\n        errval = data[9:].decode(\"utf-8\", \"replace\")\n        errorclass = error_map.get(errno)\n        if errorclass is None:\n            errorclass = InternalError if errno < 1000 else OperationalError\n>       raise errorclass(errno, errval)\nE       pymysql.err.OperationalError: (1049, \"Unknown database 'data_operation_open_platform'\")\n\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\err.py:143: OperationalError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"my_fixture","time":{"start":1686643269768,"stop":1686643269776,"duration":8},"status":"broken","statusMessage":"pymysql.err.OperationalError: (1049, \"Unknown database 'data_operation_open_platform'\")\n","statusTrace":"  File \"C:\\Users\\shaoj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shaoj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shaoj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shaoj\\Desktop\\code\\pytest_testFile\\testcases\\conftest.py\", line 31, in my_fixture\n    mysql_client.execute(item.get(\"sqls\"))\n  File \"C:\\Users\\shaoj\\Desktop\\code\\pytest_testFile\\lib\\different_db\\mysqlclient_A.py\", line 38, in execute\n    with pymysql.connect(host=self.host,\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shaoj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\connections.py\", line 352, in __init__\n    self.connect()\n  File \"C:\\Users\\shaoj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\connections.py\", line 636, in connect\n    self._request_authentication()\n  File \"C:\\Users\\shaoj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\connections.py\", line 911, in _request_authentication\n    auth_packet = self._read_packet()\n                  ^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\shaoj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\connections.py\", line 729, in _read_packet\n    packet.raise_for_error()\n  File \"C:\\Users\\shaoj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\protocol.py\", line 221, in raise_for_error\n    err.raise_mysql_exception(self._data)\n  File \"C:\\Users\\shaoj\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pymysql\\err.py\", line 143, in raise_mysql_exception\n    raise errorclass(errno, errval)\n","steps":[],"attachments":[],"parameters":[],"attachmentsCount":0,"shouldDisplayMessage":true,"stepsCount":0,"hasContent":true}],"afterStages":[],"labels":[{"name":"feature","value":"测试接口"},{"name":"parentSuite","value":"testcases.test_A.test_organization"},{"name":"suite","value":"test_enableOrganization"},{"name":"subSuite","value":"TestCaseCommon"},{"name":"host","value":"admin"},{"name":"thread","value":"12684-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcases.test_A.test_organization.test_enableOrganization"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"kwargs","value":"{'apis': [{'name': '启用组织 01', 'setup': [{'type': 'db', 'sqls': 'update ums_organization set is_able = 0 where id = 35;'}], 'data': {'path': '/ums/organization/enableOrganization', 'method': 'post', 'headers': None, 'json': {'timestamp': None, 'organizationNoList': [35]}}, 'assert': [{'type': 'status', 'expect': 200}, {'type': 'sys', 'name': 'message', 'expect': '操作成功'}]}]}"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"382d6e52f6911278.json","parameterValues":["{'apis': [{'name': '启用组织 01', 'setup': [{'type': 'db', 'sqls': 'update ums_organization set is_able = 0 where id = 35;'}], 'data': {'path': '/ums/organization/enableOrganization', 'method': 'post', 'headers': None, 'json': {'timestamp': None, 'organizationNoList': [35]}}, 'assert': [{'type': 'status', 'expect': 200}, {'type': 'sys', 'name': 'message', 'expect': '操作成功'}]}]}"]}